# @generated by protocol/scripts/generate.mjs from protocol/schema/protocol.v1.json
# Do not edit by hand. Run `npm run protocol` at the repo root.
"""Wire contract between the vest (Python), the phone (TypeScript) and the cloud.
This file is the ONLY source of truth. Do not hand-edit the generated TS or Python;
edit this file and run `npm run generate` in protocol/."""

from __future__ import annotations

from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, ConfigDict, Field

PROTOCOL_VERSION = 1

# How a clip stopped recording. Drives a badge on the clip row.
ClosedBy = Literal["button", "timeout", "recovered", "manual"]
ClosedBy_VALUES: tuple[str, ...] = ("button", "timeout", "recovered", "manual",)

# Phone-local lifecycle of a clip. The vest never sees this.
ClipStatus = Literal["announced", "downloading", "verifying", "ready", "failed", "expired"]
ClipStatus_VALUES: tuple[str, ...] = ("announced", "downloading", "verifying", "ready", "failed", "expired",)

# Vest capture state machine, see spec 7.6.
SessionState = Literal["idle", "recording"]
SessionState_VALUES: tuple[str, ...] = ("idle", "recording",)

# Phone-local view of the control channel.
ConnectionState = Literal["disconnected", "connecting", "connected", "reconnecting"]
ConnectionState_VALUES: tuple[str, ...] = ("disconnected", "connecting", "connected", "reconnecting",)

# Which end the vest is standing at. One vest in v1; the field exists so a second unit needs no protocol change.
UmpireEnd = Literal["bowlers", "square_leg"]
UmpireEnd_VALUES: tuple[str, ...] = ("bowlers", "square_leg",)

# Why a clip is exempt from auto-purge. Free-text is not allowed: pin reasons end up in an audit log and must be enumerable.
PinReason = Literal["wicket", "review", "no_ball", "incident", "other"]
PinReason_VALUES: tuple[str, ...] = ("wicket", "review", "no_ball", "incident", "other",)

AppealType = Literal["lbw", "caught", "runout", "stumping", "noball", "other"]
AppealType_VALUES: tuple[str, ...] = ("lbw", "caught", "runout", "stumping", "noball", "other",)

Decision = Literal["out", "not_out", "inconclusive"]
Decision_VALUES: tuple[str, ...] = ("out", "not_out", "inconclusive",)

class ClipMeta(BaseModel):
    """The sidecar the vest writes next to every clip, and the payload of GET /api/clips."""
    model_config = ConfigDict(extra="forbid")

    v: int = Field(..., description="Protocol version this object was written by.")
    match_id: str = Field(..., description="Opaque match identifier minted by the vest. Contains no personal data.")
    camera_id: str = Field(..., description="Stable id of the vest unit. Present from v1 so a second unit is additive.")
    seq: int = Field(..., description="Monotonic delivery counter. Wides and no-balls get their own seq.")
    started_at: float = Field(..., description="Unix seconds, vest clock, including pre-roll.")
    ended_at: float = Field(..., description="Unix seconds, vest clock.")
    duration_s: float
    preroll_s: float = Field(..., description="Seconds of ring buffer prepended before the START press.")
    closed_by: ClosedBy
    resolution: str = Field(..., description="WxH, e.g. 1920x1200.")
    fps: float
    codec: str
    bytes: int
    sha256: str = Field(..., description="Lowercase hex of the review-copy file. The phone must verify this before committing.")
    over: int | None = Field(..., description="Nullable: the vest does not know the score. The phone fills it in.")
    ball_in_over: int | None
    legal: bool = Field(..., description="False for a wide or a no-ball.")


class HealthSnapshot(BaseModel):
    """Vest telemetry. Deliberately carries no video and no identifiers beyond camera_id."""
    model_config = ConfigDict(extra="forbid")

    battery_pct: float
    temp_c: float
    disk_free_gb: float
    encoder_fps: float = Field(..., description="Measured, not configured. A silent drop here is the worst failure mode in the system.")
    clips_held: int
    remote_battery_pct: float | None = Field(default=None, description="Battery of the BLE remote, null if the remote has never reported.")


class HelloMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["hello"] = "hello"
    camera_id: str
    match_id: str | None
    seq_latest: int
    protocol: int = Field(..., description="Highest protocol version the vest speaks. The phone refuses to pair on a major mismatch.")
    firmware: str
    end: UmpireEnd | None = Field(default=None)
    ring_size: int | None = Field(default=None, description="How many clips the vest holds. The phone mirrors this rather than hardcoding 12.")


class ClipReadyMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["clip_ready"] = "clip_ready"
    seq: int
    camera_id: str
    bytes: int
    sha256: str
    duration_s: float
    closed_by: ClosedBy


class ClipExpiredMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["clip_expired"] = "clip_expired"
    seq: int
    camera_id: str


class SessionStateMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["session_state"] = "session_state"
    camera_id: str
    state: SessionState
    seq: int
    since: float


class StatusMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["status"] = "status"
    camera_id: str
    health: HealthSnapshot


class PongMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["pong"] = "pong"
    t: float = Field(..., description="Echo of the client ping timestamp, for RTT.")


class AckMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["ack"] = "ack"
    seq: int
    sha256: str


class PinMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["pin"] = "pin"
    seq: int
    pinned: bool
    reason: PinReason


class PingMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["ping"] = "ping"
    t: float


class ResyncMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    v: int
    type: Literal["resync"] = "resync"
    since_seq: int = Field(..., description="Highest seq the phone has committed. The vest replays everything after it that is still held.")


# Vest to phone. Unknown types are ignored, never an error, so either side upgrades independently.
ServerMessage = Annotated[
    Union[HelloMessage, ClipReadyMessage, ClipExpiredMessage, SessionStateMessage, StatusMessage, PongMessage],
    Field(discriminator="type"),
]

# Phone to vest.
ClientMessage = Annotated[
    Union[AckMessage, PinMessage, PingMessage, ResyncMessage],
    Field(discriminator="type"),
]

class PairingPayload(BaseModel):
    """The contents of the QR code on the vest. Scanned once per season, not per match."""
    model_config = ConfigDict(extra="forbid")

    v: int
    ssid: str
    password: str = Field(..., description="WPA2 passphrase for the vest AP. Secret: never logged, never rendered, never synced.")
    host: str = Field(..., description="e.g. 192.168.43.1")
    camera_id: str
    psk: str | None = Field(default=None, description="Optional 32-byte hex shared secret. When present the phone HMACs every request so another phone on the same AP cannot pull clips. See docs/THREAT_MODEL.md.")
    end: UmpireEnd | None = Field(default=None)


__all__ = [
    "PROTOCOL_VERSION",
    "ClosedBy",
    "ClipStatus",
    "SessionState",
    "ConnectionState",
    "UmpireEnd",
    "PinReason",
    "AppealType",
    "Decision",
    "ClipMeta",
    "HealthSnapshot",
    "HelloMessage",
    "ClipReadyMessage",
    "ClipExpiredMessage",
    "SessionStateMessage",
    "StatusMessage",
    "PongMessage",
    "AckMessage",
    "PinMessage",
    "PingMessage",
    "ResyncMessage",
    "ServerMessage",
    "ClientMessage",
    "PairingPayload",
]
