// @generated by protocol/scripts/generate.mjs from protocol/schema/protocol.v1.json
// Do not edit by hand. Run `npm run protocol` at the repo root.

/**
 * Wire contract between the vest (Python), the phone (TypeScript) and the cloud.
 * This file is the ONLY source of truth. Do not hand-edit the generated TS or Python;
 * edit this file and run `npm run generate` in protocol/.
 */
export const PROTOCOL_VERSION = 1;

/** How a clip stopped recording. Drives a badge on the clip row. */
export type ClosedBy = "button" | "timeout" | "recovered" | "manual";
export const ClosedBy_VALUES = ["button", "timeout", "recovered", "manual"] as const;

/** Phone-local lifecycle of a clip. The vest never sees this. */
export type ClipStatus = "announced" | "downloading" | "verifying" | "ready" | "failed" | "expired";
export const ClipStatus_VALUES = ["announced", "downloading", "verifying", "ready", "failed", "expired"] as const;

/** Vest capture state machine, see spec 7.6. */
export type SessionState = "idle" | "recording";
export const SessionState_VALUES = ["idle", "recording"] as const;

/** Phone-local view of the control channel. */
export type ConnectionState = "disconnected" | "connecting" | "connected" | "reconnecting";
export const ConnectionState_VALUES = ["disconnected", "connecting", "connected", "reconnecting"] as const;

/** Which end the vest is standing at. One vest in v1; the field exists so a second unit needs no protocol change. */
export type UmpireEnd = "bowlers" | "square_leg";
export const UmpireEnd_VALUES = ["bowlers", "square_leg"] as const;

/** Which edge of a delivery a marker represents. The umpire marks the start and the end from the app; the vest cuts the clip out of its rolling buffer afterwards. */
export type MarkEdge = "start" | "end";
export const MarkEdge_VALUES = ["start", "end"] as const;

/** Why the vest could not use a marker. Every value is something the phone can explain to the umpire, because a tap that produced nothing and said nothing is the failure this whole design exists to avoid. */
export type RefusalReason = "no_match" | "too_old" | "buffer_miss" | "cut_failed";
export const RefusalReason_VALUES = ["no_match", "too_old", "buffer_miss", "cut_failed"] as const;

/** Why a clip is exempt from auto-purge. Free-text is not allowed: pin reasons end up in an audit log and must be enumerable. */
export type PinReason = "wicket" | "review" | "no_ball" | "incident" | "other";
export const PinReason_VALUES = ["wicket", "review", "no_ball", "incident", "other"] as const;


export type AppealType = "lbw" | "caught" | "runout" | "stumping" | "noball" | "other";
export const AppealType_VALUES = ["lbw", "caught", "runout", "stumping", "noball", "other"] as const;


export type Decision = "out" | "not_out" | "inconclusive";
export const Decision_VALUES = ["out", "not_out", "inconclusive"] as const;

/** The sidecar the vest writes next to every clip, and the payload of GET /api/clips. */
export interface ClipMeta {
  /** Protocol version this object was written by. */
  v: number;
  /** Opaque match identifier minted by the vest. Contains no personal data. */
  match_id: string;
  /** Stable id of the vest unit. Present from v1 so a second unit is additive. */
  camera_id: string;
  /** Monotonic delivery counter. Wides and no-balls get their own seq. */
  seq: number;
  /** Unix seconds, vest clock, including pre-roll. */
  started_at: number;
  /** Unix seconds, vest clock. */
  ended_at: number;
  duration_s: number;
  /** Seconds of ring buffer prepended before the START press. */
  preroll_s: number;
  closed_by: ClosedBy;
  /** Measured from the file, and null when it could not be measured. Not defaulted to a plausible value: a wrong frame rate is a stepping control that lies, and nothing downstream can tell it is wrong. */
  resolution: string | null;
  /** Measured from the file, and null when it could not be measured. Not defaulted to a plausible value: a wrong frame rate is a stepping control that lies, and nothing downstream can tell it is wrong. */
  fps: number | null;
  /** Measured from the file, and null when it could not be measured. Not defaulted to a plausible value: a wrong frame rate is a stepping control that lies, and nothing downstream can tell it is wrong. */
  codec: string | null;
  bytes: number;
  /** Lowercase hex of the review-copy file. The phone must verify this before committing. */
  sha256: string;
  /** Nullable: the vest does not know the score. The phone fills it in. */
  over: number | null;
  ball_in_over: number | null;
  /** False for a wide or a no-ball. */
  legal: boolean;
}

/** Vest telemetry. Deliberately carries no video and no identifiers beyond camera_id. */
export interface HealthSnapshot {
  /** Null when the vest has no gauge. Not 100: a fabricated full battery on a vest running off one is the worst possible lie. */
  battery_pct: number | null;
  /** Board temperature, or null where it cannot be read. A vest is an insulated box in the sun and this is what throttles first. */
  temp_c: number | null;
  disk_free_gb: number;
  /** Measured, not configured. A silent drop here is the worst failure mode in the system. */
  encoder_fps: number;
  clips_held: number;
  /** How many seconds of footage are currently recoverable from the rolling buffer. A marker older than this can no longer be cut, which is the one thing the phone needs to know before promising the umpire a clip. */
  buffer_held_s: number;
  /** Whether footage is actually reaching the disk - not whether a process exists. The phone cannot see the vest, so this is the only way an umpire learns the camera has stopped before a tap produces nothing. */
  recording: boolean | null;
}


export interface HelloMessage {
  v: number;
  type: "hello";
  camera_id: string;
  match_id: string | null;
  seq_latest: number;
  /** Highest protocol version the vest speaks. The phone refuses to pair on a major mismatch. */
  protocol: number;
  firmware: string;
  end?: UmpireEnd;
  /** How many clips the vest holds. The phone mirrors this rather than hardcoding 12. */
  ring_size?: number;
  /** Depth of the rolling capture buffer. Anything within this window can still be cut, which is what makes a marker queued during a Wi-Fi outage recoverable. */
  buffer_seconds?: number;
  /** Seconds of run-up the vest adds before every marker. The vest's setting, not the phone's - the phone cannot change it and should show this rather than a control of its own. */
  preroll_seconds?: number | null;
}


export interface ClipReadyMessage {
  v: number;
  type: "clip_ready";
  seq: number;
  camera_id: string;
  bytes: number;
  sha256: string;
  duration_s: number;
  closed_by: ClosedBy;
  /** Measured from the file the vest just wrote, e.g. 1296x972. Absent from vests built before this field existed. */
  resolution?: string | null;
  /** Measured frame rate. The review screen steps frames with this, so a guess here is a stepping control that lies. */
  fps?: number | null;
  /** Measured codec, e.g. h264. */
  codec?: string | null;
  /** Seconds of run-up the vest actually included, which is the vest's setting and not the phone's. */
  preroll_s?: number | null;
}


export interface ClipExpiredMessage {
  v: number;
  type: "clip_expired";
  seq: number;
  camera_id: string;
}

/**
 * A marker arrived and produced no clip.
 * 
 * The vest used to drop these silently. That is the worst thing it can do: the umpire taps, nothing appears, and there is nothing anywhere to say why. Refusing out loud lets the phone put a reason on screen and decide whether to try again.
 */
export interface MarkerRefusedMessage {
  v: number;
  type: "marker_refused";
  seq: number;
  edge: MarkEdge;
  reason: RefusalReason;
  /** Free text for the diagnostics screen. Never shown to the umpire. */
  detail?: string | null;
}


export interface SessionStateMessage {
  v: number;
  type: "session_state";
  camera_id: string;
  state: SessionState;
  seq: number;
  since: number;
}


export interface StatusMessage {
  v: number;
  type: "status";
  camera_id: string;
  health: HealthSnapshot;
}


export interface PongMessage {
  v: number;
  type: "pong";
  /** Echo of the client ping timestamp, for RTT. */
  t: number;
  /** The vest's own clock at the moment it replied. With the round trip from `t`, the phone estimates the offset between the two clocks and stamps every marker in vest time - so the vest never has to track a per-client offset of its own. */
  vest_time?: number;
}


export interface AckMessage {
  v: number;
  type: "ack";
  seq: number;
  sha256: string;
}


export interface PinMessage {
  v: number;
  type: "pin";
  seq: number;
  pinned: boolean;
  reason: PinReason;
}

/**
 * The umpire marked the start or the end of a delivery. Replaces the BLE remote: the control now lives in the app, next to the footage.
 * 
 * A marker is not a trigger. The vest records continuously, so this only says which part of the buffer to keep. That is what lets a marker queued during a Wi-Fi outage still produce a clip once the link returns - the footage was never conditional on the message arriving.
 */
export interface MarkMessage {
  v: number;
  type: "mark";
  /** Delivery number. Minted by the phone, which is now the thing that counts deliveries. */
  seq: number;
  edge: MarkEdge;
  /** Unix seconds in the VEST's clock, already offset-corrected by the phone. See `vest_time` on the pong message. */
  at: number;
  /** True when this marker was held on the phone during an outage and is being replayed. The vest treats it identically; the flag exists so a late clip can be explained rather than looking like a fault. */
  queued?: boolean;
}


export interface PingMessage {
  v: number;
  type: "ping";
  t: number;
}


export interface ResyncMessage {
  v: number;
  type: "resync";
  /** Highest seq the phone has committed. The vest replays everything after it that is still held. */
  since_seq: number;
}

/** Vest to phone. Unknown types are ignored, never an error, so either side upgrades independently. */
export type ServerMessage =
  | HelloMessage
  | ClipReadyMessage
  | ClipExpiredMessage
  | SessionStateMessage
  | MarkerRefusedMessage
  | StatusMessage
  | PongMessage;

/** Phone to vest. */
export type ClientMessage =
  | AckMessage
  | PinMessage
  | MarkMessage
  | PingMessage
  | ResyncMessage;

/** The contents of the QR code on the vest. Scanned once per season, not per match. */
export interface PairingPayload {
  v: number;
  ssid: string;
  /** WPA2 passphrase for the vest AP, or null where the vest does not know it - which is any vest whose network was not made by scripts/setup-hotspot.sh. Secret: never logged, never rendered, never synced. */
  password: string | null;
  /** e.g. 192.168.43.1 */
  host: string;
  camera_id: string;
  /** Optional 32-byte hex shared secret. When present the phone HMACs every request so another phone on the same AP cannot pull clips. See docs/THREAT_MODEL.md. */
  psk?: string | null;
  end?: UmpireEnd;
}

const SERVERMESSAGE_REQUIRED: Record<string, readonly string[]> = {
  "hello": [
    "v",
    "camera_id",
    "match_id",
    "seq_latest",
    "protocol",
    "firmware"
  ],
  "clip_ready": [
    "v",
    "seq",
    "camera_id",
    "bytes",
    "sha256",
    "duration_s",
    "closed_by"
  ],
  "clip_expired": [
    "v",
    "seq",
    "camera_id"
  ],
  "session_state": [
    "v",
    "state",
    "seq",
    "since",
    "camera_id"
  ],
  "marker_refused": [
    "v",
    "seq",
    "edge",
    "reason"
  ],
  "status": [
    "v",
    "camera_id",
    "health"
  ],
  "pong": [
    "v",
    "t"
  ]
};

/**
 * Narrows an untrusted value to a ServerMessage, or returns null.
 * Unknown `type` values return null rather than throwing: the protocol
 * rule is that either side may be upgraded independently, so an unrecognised
 * message is something to ignore, not an error to surface.
 */
export function parseServerMessage(raw: unknown): ServerMessage | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const m = raw as Record<string, unknown>;
  const tag = m.type;
  if (typeof tag !== 'string') return null;
  const required = SERVERMESSAGE_REQUIRED[tag];
  if (!required) return null;
  for (const key of required) if (m[key] === undefined) return null;
  return m as unknown as ServerMessage;
}

const CLIENTMESSAGE_REQUIRED: Record<string, readonly string[]> = {
  "ack": [
    "v",
    "seq",
    "sha256"
  ],
  "pin": [
    "v",
    "seq",
    "pinned",
    "reason"
  ],
  "mark": [
    "v",
    "seq",
    "edge",
    "at"
  ],
  "ping": [
    "v",
    "t"
  ],
  "resync": [
    "v",
    "since_seq"
  ]
};

/**
 * Narrows an untrusted value to a ClientMessage, or returns null.
 * Unknown `type` values return null rather than throwing: the protocol
 * rule is that either side may be upgraded independently, so an unrecognised
 * message is something to ignore, not an error to surface.
 */
export function parseClientMessage(raw: unknown): ClientMessage | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const m = raw as Record<string, unknown>;
  const tag = m.type;
  if (typeof tag !== 'string') return null;
  const required = CLIENTMESSAGE_REQUIRED[tag];
  if (!required) return null;
  for (const key of required) if (m[key] === undefined) return null;
  return m as unknown as ClientMessage;
}

