// @generated by protocol/scripts/generate.mjs from protocol/schema/protocol.v1.json
// Do not edit by hand. Run `npm run protocol` at the repo root.

/**
 * Wire contract between the vest (Python), the phone (TypeScript) and the cloud.
 * This file is the ONLY source of truth. Do not hand-edit the generated TS or Python;
 * edit this file and run `npm run generate` in protocol/.
 */
export const PROTOCOL_VERSION = 1;

/** How a clip stopped recording. Drives a badge on the clip row. */
export type ClosedBy = "button" | "timeout" | "recovered" | "manual";
export const ClosedBy_VALUES = ["button", "timeout", "recovered", "manual"] as const;

/** Phone-local lifecycle of a clip. The vest never sees this. */
export type ClipStatus = "announced" | "downloading" | "verifying" | "ready" | "failed" | "expired";
export const ClipStatus_VALUES = ["announced", "downloading", "verifying", "ready", "failed", "expired"] as const;

/** Vest capture state machine, see spec 7.6. */
export type SessionState = "idle" | "recording";
export const SessionState_VALUES = ["idle", "recording"] as const;

/** Phone-local view of the control channel. */
export type ConnectionState = "disconnected" | "connecting" | "connected" | "reconnecting";
export const ConnectionState_VALUES = ["disconnected", "connecting", "connected", "reconnecting"] as const;

/** Which end the vest is standing at. One vest in v1; the field exists so a second unit needs no protocol change. */
export type UmpireEnd = "bowlers" | "square_leg";
export const UmpireEnd_VALUES = ["bowlers", "square_leg"] as const;

/** Why a clip is exempt from auto-purge. Free-text is not allowed: pin reasons end up in an audit log and must be enumerable. */
export type PinReason = "wicket" | "review" | "no_ball" | "incident" | "other";
export const PinReason_VALUES = ["wicket", "review", "no_ball", "incident", "other"] as const;


export type AppealType = "lbw" | "caught" | "runout" | "stumping" | "noball" | "other";
export const AppealType_VALUES = ["lbw", "caught", "runout", "stumping", "noball", "other"] as const;


export type Decision = "out" | "not_out" | "inconclusive";
export const Decision_VALUES = ["out", "not_out", "inconclusive"] as const;

/** The sidecar the vest writes next to every clip, and the payload of GET /api/clips. */
export interface ClipMeta {
  /** Protocol version this object was written by. */
  v: number;
  /** Opaque match identifier minted by the vest. Contains no personal data. */
  match_id: string;
  /** Stable id of the vest unit. Present from v1 so a second unit is additive. */
  camera_id: string;
  /** Monotonic delivery counter. Wides and no-balls get their own seq. */
  seq: number;
  /** Unix seconds, vest clock, including pre-roll. */
  started_at: number;
  /** Unix seconds, vest clock. */
  ended_at: number;
  duration_s: number;
  /** Seconds of ring buffer prepended before the START press. */
  preroll_s: number;
  closed_by: ClosedBy;
  /** WxH, e.g. 1920x1200. */
  resolution: string;
  fps: number;
  codec: string;
  bytes: number;
  /** Lowercase hex of the review-copy file. The phone must verify this before committing. */
  sha256: string;
  /** Nullable: the vest does not know the score. The phone fills it in. */
  over: number | null;
  ball_in_over: number | null;
  /** False for a wide or a no-ball. */
  legal: boolean;
}

/** Vest telemetry. Deliberately carries no video and no identifiers beyond camera_id. */
export interface HealthSnapshot {
  battery_pct: number;
  temp_c: number;
  disk_free_gb: number;
  /** Measured, not configured. A silent drop here is the worst failure mode in the system. */
  encoder_fps: number;
  clips_held: number;
  /** Battery of the BLE remote, null if the remote has never reported. */
  remote_battery_pct?: number | null;
}


export interface HelloMessage {
  v: number;
  type: "hello";
  camera_id: string;
  match_id: string | null;
  seq_latest: number;
  /** Highest protocol version the vest speaks. The phone refuses to pair on a major mismatch. */
  protocol: number;
  firmware: string;
  end?: UmpireEnd;
  /** How many clips the vest holds. The phone mirrors this rather than hardcoding 12. */
  ring_size?: number;
}


export interface ClipReadyMessage {
  v: number;
  type: "clip_ready";
  seq: number;
  camera_id: string;
  bytes: number;
  sha256: string;
  duration_s: number;
  closed_by: ClosedBy;
}


export interface ClipExpiredMessage {
  v: number;
  type: "clip_expired";
  seq: number;
  camera_id: string;
}


export interface SessionStateMessage {
  v: number;
  type: "session_state";
  camera_id: string;
  state: SessionState;
  seq: number;
  since: number;
}


export interface StatusMessage {
  v: number;
  type: "status";
  camera_id: string;
  health: HealthSnapshot;
}


export interface PongMessage {
  v: number;
  type: "pong";
  /** Echo of the client ping timestamp, for RTT. */
  t: number;
}


export interface AckMessage {
  v: number;
  type: "ack";
  seq: number;
  sha256: string;
}


export interface PinMessage {
  v: number;
  type: "pin";
  seq: number;
  pinned: boolean;
  reason: PinReason;
}


export interface PingMessage {
  v: number;
  type: "ping";
  t: number;
}


export interface ResyncMessage {
  v: number;
  type: "resync";
  /** Highest seq the phone has committed. The vest replays everything after it that is still held. */
  since_seq: number;
}

/** Vest to phone. Unknown types are ignored, never an error, so either side upgrades independently. */
export type ServerMessage =
  | HelloMessage
  | ClipReadyMessage
  | ClipExpiredMessage
  | SessionStateMessage
  | StatusMessage
  | PongMessage;

/** Phone to vest. */
export type ClientMessage =
  | AckMessage
  | PinMessage
  | PingMessage
  | ResyncMessage;

/** The contents of the QR code on the vest. Scanned once per season, not per match. */
export interface PairingPayload {
  v: number;
  ssid: string;
  /** WPA2 passphrase for the vest AP. Secret: never logged, never rendered, never synced. */
  password: string;
  /** e.g. 192.168.43.1 */
  host: string;
  camera_id: string;
  /** Optional 32-byte hex shared secret. When present the phone HMACs every request so another phone on the same AP cannot pull clips. See docs/THREAT_MODEL.md. */
  psk?: string | null;
  end?: UmpireEnd;
}

const SERVERMESSAGE_REQUIRED: Record<string, readonly string[]> = {
  "hello": [
    "v",
    "camera_id",
    "match_id",
    "seq_latest",
    "protocol",
    "firmware"
  ],
  "clip_ready": [
    "v",
    "seq",
    "camera_id",
    "bytes",
    "sha256",
    "duration_s",
    "closed_by"
  ],
  "clip_expired": [
    "v",
    "seq",
    "camera_id"
  ],
  "session_state": [
    "v",
    "state",
    "seq",
    "since",
    "camera_id"
  ],
  "status": [
    "v",
    "camera_id",
    "health"
  ],
  "pong": [
    "v",
    "t"
  ]
};

/**
 * Narrows an untrusted value to a ServerMessage, or returns null.
 * Unknown `type` values return null rather than throwing: the protocol
 * rule is that either side may be upgraded independently, so an unrecognised
 * message is something to ignore, not an error to surface.
 */
export function parseServerMessage(raw: unknown): ServerMessage | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const m = raw as Record<string, unknown>;
  const tag = m.type;
  if (typeof tag !== 'string') return null;
  const required = SERVERMESSAGE_REQUIRED[tag];
  if (!required) return null;
  for (const key of required) if (m[key] === undefined) return null;
  return m as unknown as ServerMessage;
}

const CLIENTMESSAGE_REQUIRED: Record<string, readonly string[]> = {
  "ack": [
    "v",
    "seq",
    "sha256"
  ],
  "pin": [
    "v",
    "seq",
    "pinned",
    "reason"
  ],
  "ping": [
    "v",
    "t"
  ],
  "resync": [
    "v",
    "since_seq"
  ]
};

/**
 * Narrows an untrusted value to a ClientMessage, or returns null.
 * Unknown `type` values return null rather than throwing: the protocol
 * rule is that either side may be upgraded independently, so an unrecognised
 * message is something to ignore, not an error to surface.
 */
export function parseClientMessage(raw: unknown): ClientMessage | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const m = raw as Record<string, unknown>;
  const tag = m.type;
  if (typeof tag !== 'string') return null;
  const required = CLIENTMESSAGE_REQUIRED[tag];
  if (!required) return null;
  for (const key of required) if (m[key] === undefined) return null;
  return m as unknown as ClientMessage;
}

