#!/usr/bin/env node
/**
 * Generates the TypeScript and Python views of the wire protocol from
 * schema/protocol.v1.json.
 *
 * Zero dependencies on purpose: this runs in CI, on the ROCK, and on a laptop
 * with no network, and it must never be the reason a build fails.
 *
 *   node scripts/generate.mjs           write the generated files
 *   node scripts/generate.mjs --check   exit 1 if they are out of date
 *
 * Handled subset of JSON Schema: object/string/number/integer/boolean, const,
 * string enum, $ref, arrays, nullable via type unions, and oneOf with an
 * x-discriminator. That is all the protocol needs and all this understands.
 * If you reach for something outside it, extend this file rather than
 * hand-editing the output.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const REPO = resolve(ROOT, '..');

const schema = JSON.parse(readFileSync(join(ROOT, 'schema/protocol.v1.json'), 'utf8'));
const defs = schema.$defs;
const VERSION = schema['x-protocolVersion'];

const check = process.argv.includes('--check');
const refName = (r) => r.replace('#/$defs/', '');

/* ---------- shape classification ---------- */

const kindOf = (d) => {
  if (d.oneOf) return 'union';
  if (d.enum) return 'enum';
  if (d.type === 'object') return 'object';
  throw new Error(`unsupported def: ${JSON.stringify(d).slice(0, 120)}`);
};

/** Definitions must be emitted after anything they reference (Python needs it). */
function topoSort(names) {
  const deps = (d) => {
    const out = [];
    const walk = (n) => {
      if (!n || typeof n !== 'object') return;
      if (n.$ref) out.push(refName(n.$ref));
      for (const v of Object.values(n)) {
        if (Array.isArray(v)) v.forEach(walk);
        else if (v && typeof v === 'object') walk(v);
      }
    };
    walk(d);
    return out;
  };
  const seen = new Set();
  const order = [];
  const visit = (name, stack = []) => {
    if (seen.has(name)) return;
    if (stack.includes(name)) throw new Error(`cycle: ${[...stack, name].join(' -> ')}`);
    for (const dep of deps(defs[name])) visit(dep, [...stack, name]);
    seen.add(name);
    order.push(name);
  };
  names.forEach((n) => visit(n));
  return order;
}

const ORDER = topoSort(Object.keys(defs));

/* ---------- TypeScript ---------- */

function tsType(p) {
  if (p.$ref) return refName(p.$ref);
  if (p.const !== undefined) return JSON.stringify(p.const);
  if (p.enum) return p.enum.map((e) => JSON.stringify(e)).join(' | ');
  const types = Array.isArray(p.type) ? p.type : [p.type];
  const base = types
    .filter((t) => t !== 'null')
    .map((t) => ({ string: 'string', number: 'number', integer: 'number', boolean: 'boolean' }[t] ?? 'unknown'));
  if (p.type === 'array') return `${tsType(p.items)}[]`;
  return types.includes('null') ? [...base, 'null'].join(' | ') : base.join(' | ');
}

function tsDoc(text, indent = '') {
  if (!text) return '';
  const lines = String(text).split('\n');
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
  return `${indent}/**\n${lines.map((l) => `${indent} * ${l}`).join('\n')}\n${indent} */\n`;
}

function emitTs() {
  const out = [];
  out.push('// @generated by protocol/scripts/generate.mjs from protocol/schema/protocol.v1.json');
  out.push('// Do not edit by hand. Run `npm run protocol` at the repo root.');
  out.push('');
  out.push(tsDoc(schema.description).trimEnd());
  out.push(`export const PROTOCOL_VERSION = ${VERSION};`);
  out.push('');

  for (const name of ORDER) {
    const d = defs[name];
    const kind = kindOf(d);
    out.push(tsDoc(d.description).trimEnd());
    if (kind === 'enum') {
      out.push(`export type ${name} = ${d.enum.map((e) => JSON.stringify(e)).join(' | ')};`);
      out.push(`export const ${name}_VALUES = [${d.enum.map((e) => JSON.stringify(e)).join(', ')}] as const;`);
    } else if (kind === 'union') {
      out.push(`export type ${name} =\n${d.oneOf.map((o) => `  | ${refName(o.$ref)}`).join('\n')};`);
    } else {
      const req = new Set(d.required ?? []);
      const body = Object.entries(d.properties).map(([k, p]) => {
        const doc = tsDoc(p.description, '  ');
        return `${doc}  ${k}${req.has(k) ? '' : '?'}: ${tsType(p)};`;
      });
      out.push(`export interface ${name} {\n${body.join('\n')}\n}`);
    }
    out.push('');
  }

  // Runtime guards. Messages arrive off a socket; the type system stops at the
  // boundary and something has to check the shape on the other side of it.
  for (const unionName of ORDER.filter((n) => defs[n].oneOf && defs[n]['x-discriminator'])) {
    const disc = defs[unionName]['x-discriminator'];
    const variants = defs[unionName].oneOf.map((o) => refName(o.$ref));
    const tags = variants.map((v) => defs[v].properties[disc].const);
    const required = Object.fromEntries(
      variants.map((v, i) => [tags[i], (defs[v].required ?? []).filter((r) => r !== disc)])
    );
    const lower = unionName[0].toLowerCase() + unionName.slice(1);
    out.push(`const ${unionName.toUpperCase()}_REQUIRED: Record<string, readonly string[]> = ${JSON.stringify(required, null, 2)};`);
    out.push('');
    out.push(`/**
 * Narrows an untrusted value to a ${unionName}, or returns null.
 * Unknown \`${disc}\` values return null rather than throwing: the protocol
 * rule is that either side may be upgraded independently, so an unrecognised
 * message is something to ignore, not an error to surface.
 */
export function parse${unionName}(raw: unknown): ${unionName} | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const m = raw as Record<string, unknown>;
  const tag = m.${disc};
  if (typeof tag !== 'string') return null;
  const required = ${unionName.toUpperCase()}_REQUIRED[tag];
  if (!required) return null;
  for (const key of required) if (m[key] === undefined) return null;
  return m as unknown as ${unionName};
}`);
    out.push('');
    void lower;
  }
  return out.join('\n');
}

/* ---------- Python ---------- */

function pyType(p) {
  if (p.$ref) return refName(p.$ref);
  if (p.const !== undefined) return `Literal[${JSON.stringify(p.const)}]`;
  if (p.enum) return `Literal[${p.enum.map((e) => JSON.stringify(e)).join(', ')}]`;
  if (p.type === 'array') return `list[${pyType(p.items)}]`;
  const types = Array.isArray(p.type) ? p.type : [p.type];
  const base = types
    .filter((t) => t !== 'null')
    .map((t) => ({ string: 'str', number: 'float', integer: 'int', boolean: 'bool' }[t] ?? 'Any'));
  return types.includes('null') ? `${base.join(' | ')} | None` : base.join(' | ');
}

function pyDoc(text, indent = '    ') {
  if (!text) return '';
  const lines = String(text).split('\n');
  if (lines.length === 1) return `${indent}"""${lines[0]}"""\n`;
  return `${indent}"""\n${lines.map((l) => `${indent}${l}`).join('\n')}\n${indent}"""\n`;
}

function emitPy() {
  const out = [];
  out.push('# @generated by protocol/scripts/generate.mjs from protocol/schema/protocol.v1.json');
  out.push('# Do not edit by hand. Run `npm run protocol` at the repo root.');
  out.push('"""' + schema.description + '"""');
  out.push('');
  out.push('from __future__ import annotations');
  out.push('');
  out.push('from typing import Annotated, Any, Literal, Union');
  out.push('');
  out.push('from pydantic import BaseModel, ConfigDict, Field');
  out.push('');
  out.push(`PROTOCOL_VERSION = ${VERSION}`);
  out.push('');

  for (const name of ORDER) {
    const d = defs[name];
    const kind = kindOf(d);
    if (kind === 'enum') {
      if (d.description) out.push(`# ${d.description.split('\n').join(' ')}`);
      out.push(`${name} = Literal[${d.enum.map((e) => JSON.stringify(e)).join(', ')}]`);
      out.push(`${name}_VALUES: tuple[str, ...] = (${d.enum.map((e) => JSON.stringify(e)).join(', ')},)`);
      out.push('');
    } else if (kind === 'union') {
      const variants = d.oneOf.map((o) => refName(o.$ref));
      if (d.description) out.push(`# ${d.description.split('\n').join(' ')}`);
      const disc = d['x-discriminator'];
      out.push(`${name} = Annotated[`);
      out.push(`    Union[${variants.join(', ')}],`);
      out.push(disc ? `    Field(discriminator=${JSON.stringify(disc)}),` : '    Field(),');
      out.push(']');
      out.push('');
    } else {
      const req = new Set(d.required ?? []);
      out.push(`class ${name}(BaseModel):`);
      if (d.description) out.push(pyDoc(d.description).trimEnd());
      out.push('    model_config = ConfigDict(extra="forbid")');
      out.push('');
      for (const [k, p] of Object.entries(d.properties)) {
        const t = pyType(p);
        const parts = [];
        if (p.description) parts.push(`description=${JSON.stringify(p.description)}`);
        if (p.const !== undefined) {
          out.push(`    ${k}: ${t} = ${JSON.stringify(p.const)}`);
          continue;
        }
        if (req.has(k)) {
          out.push(parts.length ? `    ${k}: ${t} = Field(..., ${parts.join(', ')})` : `    ${k}: ${t}`);
        } else {
          out.push(`    ${k}: ${t.includes('None') ? t : `${t} | None`} = Field(default=None${parts.length ? ', ' + parts.join(', ') : ''})`);
        }
      }
      out.push('');
      out.push('');
    }
  }
  out.push('__all__ = [');
  out.push('    "PROTOCOL_VERSION",');
  for (const n of ORDER) out.push(`    "${n}",`);
  out.push(']');
  out.push('');
  return out.join('\n').replace(/\n{4,}/g, '\n\n\n');
}

/* ---------- write ---------- */

const targets = [
  { path: join(REPO, 'mobile/src/types/protocol.ts'), body: emitTs() + '\n' },
  { path: join(REPO, 'vest/thirdeye/protocol.py'), body: emitPy() },
];

let stale = 0;
for (const { path, body } of targets) {
  let current = null;
  try { current = readFileSync(path, 'utf8'); } catch { /* first run */ }
  if (current === body) { console.log(`  ok    ${path.replace(REPO + '/', '')}`); continue; }
  stale++;
  if (check) { console.error(`  STALE ${path.replace(REPO + '/', '')}`); continue; }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
  console.log(`  write ${path.replace(REPO + '/', '')}`);
}

if (check && stale) {
  console.error('\nGenerated protocol files are out of date. Run `npm run protocol` and commit the result.');
  process.exit(1);
}
